language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

sudo: required

dist: trusty

install:
  - sudo apt-get install -y libopencv-dev g++-5

script: sbt ++$TRAVIS_SCALA_VERSION test scalastyle test:scalastyle
