language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y upgrade
  - sudo apt-get -y dist-upgrade

install:
  - sudo apt-get install -y libopencv-dev libstdc++6

script: sbt ++$TRAVIS_SCALA_VERSION test scalastyle test:scalastyle
