language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libopencv-dev libstdc++6
  - wget -O android/libs/RobotLibrary.jar https://github.com/orbotix/Sphero-Android-SDK/raw/master/library/RobotLibrary.jar

script: sbt ++$TRAVIS_SCALA_VERSION clean test android/clean android/compile scalastyle test:scalastyle \
    android/scalastyle
