language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

sudo: required

dist: trusty

before_install:
  - sudo apt-add repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade

install:
  - sudo apt-get install -y libopencv-dev libstdc++6

script: sbt ++$TRAVIS_SCALA_VERSION test scalastyle test:scalastyle
